# Architecture identifier.
arch = "loongarch64"
# Platform identifier.
platform = "loongarch64-qemu-virt"
# Platform family.
family = "loongarch64-qemu-virt"

# Base address of the whole physical memory.
phys-memory-base = "0xA000_0000"
# Size of the whole physical memory.
phys-memory-size = "0x4000_0000"     # 128M
# Base physical address of the kernel image.
kernel-base-paddr = "0x9000_0000"
# Base virtual address of the kernel image.
kernel-base-vaddr = "0x9000_0000_9000_0000"
# Linear mapping offset, for quick conversions between physical and virtual
# addresses.
phys-virt-offset = "0x9000_0000_0000_0000"

# Testcase memory
testcase-memory-start = "0xA20C_0000"

testcase-memory-size = "0x400_0000"

# MMIO regions with format (`base_paddr`, `size`).
mmio-regions = [
    ["0x1fe2_0000", "0x1000"], # uart0
]
# VirtIO MMIO regions with format (`base_paddr`, `size`).
virtio-mmio-regions = [
]
# Base physical address of the PCIe ECAM space.
pci-ecam-base = "0x2000_0000"
# End PCI bus number (`bus-range` property in device tree).
pci-bus-end = "0x7f"
# Timer interrupt frequency in Hz.
timer-frequency = "1_00_000_000"      # 100MHz
